module.exports = {
  plugins: ["stylelint-order"],
  rules: {
    "at-rule-empty-line-before": [ "always", {
      except: [ "after-same-name" ],
    } ],
    "at-rule-semicolon-newline-after": "always",
    "order/properties-order": [
      {
        emptyLineBefore: "always",
        properties: ["content"],
      },
      {
        emptyLineBefore: "always",
        properties: ["position", "top", "right", "bottom", "left", "z-index"],
      },
      {
        emptyLineBefore: "always",
        properties: [
          "align-content",
          "align-items",
          "align-self",
          "flex",
          "flex-basis",
          "flex-direction",
          "flex-flow",
          "flex-grow",
          "flex-shrink",
          "flex-wrap",
          "justify-content",
          "order",
        ],
      },
      {
        emptyLineBefore: "always",
        properties: [
          "display",
          "max-width",
          "max-height",
          "min-width",
          "min-height",
          "width",
          "height",
          "clear",
          "float",
          "margin",
          "margin-top",
          "margin-right",
          "margin-bottom",
          "margin-left",
          "padding",
          "padding-top",
          "padding-right",
          "padding-bottom",
          "padding-left",
          "table-layout",
        ],
      },
      {
        emptyLineBefore: "always",
        properties: [
          "font-family",
          "font-size",
          "font-style",
          "font-weight",
          "letter-spacing",
          "list-style",
          "list-style-position",
          "line-height",
          "text-align",
          "text-decoration",
          "text-indent",
          "text-overflow",
          "text-transform",
        ],
      },
      {
        emptyLineBefore: "always",
        properties: [
          "appearance",
          "background",
          "background-attachment",
          "background-blend-mode",
          "background-color",
          "background-image",
          "background-position",
          "background-repeat",
          "background-size",
          "border",
          "border-top",
          "border-right",
          "border-bottom",
          "border-left",
          "border-radius",
          "border-top-left-radius",
          "border-top-right-radius",
          "border-bottom-right-radius",
          "border-bottom-left-radius",
          "box-shadow",
          "clip",
          "color",
          "cursor",
          "fill",
          "mix-blend-mode",
          "opacity",
          "overflow",
          "overflow-x",
          "overflow-y",
          "visibility",
          "will-change",
        ],
      },
      {
        emptyLineBefore: "always",
        properties: [
          "animation",
          "animation-delay",
          "animation-direction",
          "animation-duration",
          "animation-fill-mode",
          "animation-iteration-count",
          "animation-name",
          "animation-play-state",
          "animation-timing-function",
          "transform",
          "transition",
        ],
      },
    ],
    "rule-empty-line-before": "always",
    "value-list-max-empty-lines": 0
  }
}
